### ISSUE TITLE
Leaked secret key

### ISSUE THREAD

**Issue by FrankyCTY** [Coding-Crashkurse/RAG-Evaluation-with-Ragas#1]
Hey bro, just a friendly reminder that your LangFuse secret key is in the commit, and your branch is public. I recommend you to revoke the key.

Not sure if it is still a problem if your LangFuse secret key is created locally, as it could be just stored into your local docker postgres container.

**Comment by Coding-Crashkurse** [comment]
Thanks for telling me, but everything is running locally, so no worries
there. I also expose my OpenAI APIs keys in the videos, but delete them
before releasing  the video. But really appreciate your message. Thanks,
but no worries ;-)

Am Do., 17. Okt. 2024 um 20:45 Uhr schrieb Franky Chan <
***@***.***>:
